### ISSUE TITLE
I'd like to contribute - how do I get Slack 2.7.1 to show dev tools?

### ISSUE THREAD

**Issue by briantully** [widget-/slack-black-theme#14]
Thanks for making this available! My company just switched from HipChat to Slack and my eyes have been killing me due to all the BRIGHTNESS ;)

I'd like to customize the CSS even further and contribute back, but for the life of me I cannot get the DevTools web inspector to show in the latest version of Slack (2.7.1).

**Comment by widget-** [comment]
Oh I thought I had a section on that but i guess not.

The main thing is you have to `export SLACK_DEVELOPER_MENU=true`before running Slack. Then you can <kbd>Cmd</kbd><kbd>Alt</kbd><kbd>I</kbd> on Mac or <kbd>Ctrl</kbd><kbd>Alt</kbd><kbd>I</kbd> (I think?) on Windows and probably Linux to open the Inspect window (aka Devtools.)

On my Mac I have this set up as an Automator program with the "program" being `Run Shell Script` that just has

```
export SLACK_DEVELOPER_MENU=true
open -a /Applications/Slack.app
```

in it. Then I just save it as "Slack Dev Mode" and run that instead of the normal Slack app.

I'll keep this issue open until I add it to the readme.

**Comment by lucasqueiroz** [comment]
Would be great to have it perfectly working on 2.7.1 (The sidebar theme does not correctly render, at least not like the previews in the README).

**Comment by kevinraymond** [comment]
If you click nine times in the Slack Team section the DevTools will open. Only tested on Windows app, but I imagine it probably works across the board.

**Comment by catskul** [comment]
Can you describe what/where the "Slack Team section" is?

**Comment by lucasqueiroz** [comment]
The sidebar where you choose between teams.

**Comment by kevinraymond** [comment]
I think that sidebar might not be visible if you are only joined to one team.

**Comment by widget-** [comment]
Added development section to the readme, closing.

**Comment by GohioAC** [comment]
Is the development code in the readme still working?

**Comment by stamminator** [comment]
@widget- You only added it for Mac

**Comment by willpower232** [comment]
@stamminator please see https://github.com/widget-/slack-black-theme/pull/53 and https://github.com/widget-/slack-black-theme/pull/59
